---
daq_options:
 moduleNumber: test
 compressRawData: yes
 nEvent: 100
 externalChargeInjection: yes
 acquisitionType: sweep
 channelIds: [10]
 channelIdsToMask: [22]
 channelIdsDisableTOT: [22]
 channelIdsDisableTOA: [22]
 injectionDAC: 1000
 pulseDelay: 72
 preampFeedbackCapacitance: 8
 totDACThreshold: 200
glb_options:
 outputRawDataPath: data
 outputYamlPath: yaml
 storeYamlFile: yes
 startServerManually: no
 serverIpAdress: localhost
 serverCodePath: /home/pi/rpi-daq
...
